source('util.R')
source('params.R')
source('solve.R')
result <- solve(problem)

layout(matrix(c(1,2,3,3),2,2,byrow=TRUE))
color <- rainbow(length(warehouses))
matplot(result$price, t(result$payoff),type='l', main='Payoff per period', xlab='Price', ylab='Profit', col=color)
legend('topleft',legend=warehouses, col=color, pch=0)
matplot(result$price, t(result$valuefunc),type='l', main='Value-function', xlab='Price', ylab='V', col=color)
legend('topleft',legend=warehouses, col=color, pch=0)
matplot(result$price, t(result$policy),type='l', main='Optimal policy', xlab='Price', ylab='Warehouse', col=color)
legend('topleft',legend=rev(warehouses), col=rev(color), pch=0)
par(ask=TRUE)
plot.demandseries(demand,cost,duration,result$price,list(warehouse=warehouses,market=markets))